#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  if __name__ == '__main__' 
'''
作用：
一个python文件通常有两种使用方法，第一是作为脚本直接执行，第二是 import 到其他的 python 脚本中被调用（模块重用）执行。
因此 if __name__ == 'main': 的作用就是控制这两种情况执行代码的过程，在 if __name__ == 'main': 下的代码只有在第一种情况下（即文件作为脚本直接执行）才会被执行，
而 import 到其他脚本中是不会被执行的。

运行原理：
每个python模块（python文件）都包含内置的变量 __name__，当该模块被直接执行的时候，__name__ 等于__main__；当该模块 import 到其他模块中，
则该模块的 __name__ 等于模块名称（不包含后缀.py）。
'''

